services:
  nginx:
    build: ./nginx
    ports:
      - 443:443
      - 4040:4040
      - 7040:7040
    depends_on:
      - mermaid-live-editor
      - viewer
      - kroki
  mermaid-live-editor:
    image: ghcr.io/mermaid-js/mermaid-live-editor
    environment:
      - MERMAID_KROKI_RENDERER_URL=http://kroki:7000/mermaid
    ports:
      - 8000:8080
  kroki:
    image: yuzutech/kroki
    ports:
      - 7000:8000
    environment:
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_DIAGRAMSNET_HOST=diagramsnet
    depends_on:
      - blockdiag
      - mermaid
      - bpmn
  blockdiag:
    image: yuzutech/kroki-blockdiag
  mermaid:
    image: yuzutech/kroki-mermaid
  bpmn:
    image: yuzutech/kroki-bpmn
  diagramsnet:
    image: yuzutech/kroki-diagramsnet
  viewer:
    build:
      context: ./viewer
      args:
        KROKI_RENDERER_URL: https://localhost:7040/
    ports:
      - 9000:80
    depends_on:
      - kroki
